version: '3.3'
  
services:
  api:
    build:
      context: ./api/
      dockerfile: Dockerfile
    container_name: api
    volumes: ['./api:/app']
    expose:
      - '5000'
    ports:
      - '5000:5000'
    command: flask run --reload
    networks:
      - backend

networks:
  backend:
    external: true