version: '3.3'
  
services:
    db:
        image: mysql:8.2.0
        restart: always
        container_name: db
        environment:
            MYSQL_DATABASE: 'db'
            MYSQL_ROOT_PASSWORD: password'
        ports:
            - '3306:3306'
        expose:
            - '3306'
        volumes:
            - db-volume:/var/run/mysqld
            - /tmp/slack_bot/mysqld:/var/run/mysqld
            - ./init.sql:/data/application/init.sql
        command: --init-file /data/application/init.sql
    api:
        build:
            context: ./api/
            dockerfile: Dockerfile
        restart: always
        container_name: api 
        volumes: ['./api:/app', '/tmp/slack_bot/mysqld:/var/run/mysqld']
        environment:
            DB_HOST: localhost
            DB_PORT: 3306
            DB_NAME: db
            DB_USER: root
            DB_PASSWORD: ''
            DB_DRIVER: mysql
        expose:
            - '5000'
        ports:
            - '5000:5000'
        command: sh -c "flask populate-database && flask run --reload --host=0.0.0.0"
        networks:
            backend:
                aliases:
                    - db
        depends_on:
            - db
    
    app-bloxs:
        build:
            context: ./app-bloxs/
            dockerfile: Dockerfile
        container_name: app-bloxs
        volumes: ['./app-bloxs:/app']
        expose:
            - '3000'
        ports:
            - '3000:3000'
        command: npm run dev
        networks:
            - backend

networks:
    backend:
        external: true

volumes:
    db-volume: {}