"""Add email and password to Account

Revision ID: 5eaf56c0f163
Revises: 
Create Date: 2023-12-16 05:35:54.232736

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5eaf56c0f163'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.Numeric(), nullable=False))
        batch_op.drop_column('balance')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('balance', mysql.DECIMAL(precision=10, scale=0), nullable=False))
        batch_op.drop_column('amount')

    # ### end Alembic commands ###
